In [3]:
import requests
import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from bs4 import BeautifulSoup

%matplotlib inline

เลือกเฉพาะหนังจาก US ที่เป็นภาพยนตร์

In [58]:
movie = []

#2018
for i in range(1,3928,250):
    url = "https://www.imdb.com/search/title/?title_type=feature&release_date=2018-01-01,2018-12-31&countries=us&count=250&start="+str(i)
    response = requests.get(url)
    #print(response.text[:500])
    html_soup = BeautifulSoup(response.text, 'html.parser')
    #type(html_soup)
    movie_containers = html_soup.find_all('div', class_ = 'lister-item mode-advanced')
    names = []
    years = []
    genres = []
    descriptions = []

    for container in movie_containers:
    
        if (container.find('span', attrs = {'class': 'genre'}) is not None)&\
            ((container.find_all('p', attrs={'class':'text-muted'})[-1].text)!='\nAdd a Plot\n'):

            # The name
            name = container.h3.a.text
            names.append(name)

            # The year
            year = container.h3.find('span', class_ = 'lister-item-year').text
            years.append(year)

            # The genres
            genre = container.find('span', attrs = {'class': 'genre'}).text
            genres.append(genre)

            # The descriptions
            description = container.find_all('p', attrs={'class':'text-muted'})[-1].text
            descriptions.append(description)
            
    test_df = pd.DataFrame({'movie': names,
                     'year': years,
                     'genres': genres,
                     'descriptions': descriptions})
    movie.append(test_df)

In [59]:
len(movie)

16

In [66]:
movie[15]

,movie,year,genres,descriptions
0,Violent Space,(2018),\nThriller,"\nNoah Thompson, a young aspiring screenwriter..."
1,Double Fatal,(2018),\nThriller,"\nAkeya Griffin steals the heart of three men,..."
2,Comfortless,(2018),\nThriller,\nComfortless tells the story of a relationshi...
3,Who in the Hell is Lester Barrie? Comedy Special,(2018),\nComedy,\nSuper Saint features the inspiration comedia...
4,The Barrier Effect,(2018),\nDrama,\nAmidst the political climate of illegal immi...
...,...,...,...,...
98,Land of the Free,(III) (2018),"\nAdventure, Drama, War",\nA young man joins a platoon of battle-harden...
99,The Flavor,(2018),\nComedy,\nA hard-knock hustler encourages his fall-for...
100,Art House,(2018),"\nComedy, Drama, Romance",\nBest friends and roommates Mitch and Claire'...
101,Best Friends 2018,(2018),\nDrama,\nA classroom of 8th grad students each has th...
102,The Dazzle of the Midday Moon,(2018),\nDrama,\nThe multi-channel art film was inspired by t...

In [67]:
#2019
for i in range(1,3423,250):
    url = "https://www.imdb.com/search/title/?title_type=feature&release_date=2019-01-01,2019-12-31&countries=us&count=250&start="+str(i)
    response = requests.get(url)
    #print(response.text[:500])
    html_soup = BeautifulSoup(response.text, 'html.parser')
    #type(html_soup)
    movie_containers = html_soup.find_all('div', class_ = 'lister-item mode-advanced')
    names = []
    years = []
    genres = []
    descriptions = []

    for container in movie_containers:
    
        if (container.find('span', attrs = {'class': 'genre'}) is not None)&\
            ((container.find_all('p', attrs={'class':'text-muted'})[-1].text)!='\nAdd a Plot\n'):

            # The name
            name = container.h3.a.text
            names.append(name)

            # The year
            year = container.h3.find('span', class_ = 'lister-item-year').text
            years.append(year)

            # The genres
            genre = container.find('span', attrs = {'class': 'genre'}).text
            genres.append(genre)

            # The descriptions
            description = container.find_all('p', attrs={'class':'text-muted'})[-1].text
            descriptions.append(description)
            
    test_df = pd.DataFrame({'movie': names,
                     'year': years,
                     'genres': genres,
                     'descriptions': descriptions})
    movie.append(test_df)

In [68]:
len(movie)

30

In [69]:
movie[29]

,movie,year,genres,descriptions
0,Luv Gone Wrong,(2019),\nDrama,\n*SPOILERS* Brandon Wilson catches his fiance...
1,My Name is Charlie Raine,(2019),\nHorror,\nCharlie is a strange character that spends h...
2,From The Barrio to The Board Room,(2019),\nDrama,\nA kid from the barrio overcomes seemingly im...
3,Razor River,(2019),\nAction,\nWhen two people head down a river to retriev...
4,Preserving the Magic,(2019),\nComedy,\nPreserving the Magic follows the story of th...
...,...,...,...,...
79,Shindara,(2019),\nDrama,"\nShindara, a well behaved young lady finds th..."
80,Odd Love,(2019),"\nComedy, Romance","\nAfter graduating high school, Quinn realizes..."
81,The Sisters Summon,(2019),\nHorror,"\nTwo sisters, Alex and Janie, accidentally aw..."
82,The Dragonfly Conspiracy,(2019),"\nMystery, Sci-Fi, Thriller",\nAn artist and her friend become fugitives wh...
83,Matt and Kyle's Extreme Gametime: The Movie,(2019),\nComedy,"\nJoin Matt and Kyle for one last gametime, as..."

In [70]:
#2020
for i in range(1,3619,250):
    url = "https://www.imdb.com/search/title/?title_type=feature&release_date=2020-01-01,2020-12-31&countries=us&count=250&start="+str(i)
    response = requests.get(url)
    #print(response.text[:500])
    html_soup = BeautifulSoup(response.text, 'html.parser')
    #type(html_soup)
    movie_containers = html_soup.find_all('div', class_ = 'lister-item mode-advanced')
    names = []
    years = []
    genres = []
    descriptions = []

    for container in movie_containers:
    
        if (container.find('span', attrs = {'class': 'genre'}) is not None)&\
            ((container.find_all('p', attrs={'class':'text-muted'})[-1].text)!='\nAdd a Plot\n'):

            # The name
            name = container.h3.a.text
            names.append(name)

            # The year
            year = container.h3.find('span', class_ = 'lister-item-year').text
            years.append(year)

            # The genres
            genre = container.find('span', attrs = {'class': 'genre'}).text
            genres.append(genre)

            # The descriptions
            description = container.find_all('p', attrs={'class':'text-muted'})[-1].text
            descriptions.append(description)
            
    test_df = pd.DataFrame({'movie': names,
                     'year': years,
                     'genres': genres,
                     'descriptions': descriptions})
    movie.append(test_df)

In [71]:
len(movie)

45

In [72]:
movie[44]

,movie,year,genres,descriptions
0,Live Ashes,(2020),\nDrama,\nAn experimental adaptation of Shakespeare's ...
1,Jose James & Taali Live from Levon Helm Studios,(2020),\nMusic,\nCentered around the 2020 live stream perform...
2,Stink Pretty,(2020),\nDrama,\nA wire artist struggles to sell his work whi...
3,Oko Mi L'america,(2020),\nDrama,"\nA story of love, commitment, friendship and ..."
4,Kid Brainiac: Amazing Microworld,(2020),\nAnimation,\nEnter Kid Brainiac's secret lab as the mini ...
...,...,...,...,...
56,The Challenge of Flight - Go to Guns,(2020),\nWar,\nThis program traces the development of air c...
57,Comic Book Junkies,(I) (2020),\nComedy,\nA comedy focusing on a series of fans and co...
58,The Challenge of Flight - Violent Skies,(2020),\nWar,\nWitness first hand a jet that has been struc...
59,My Summer in the Chair,(2020),"\nComedy, Drama","\nSummer isn't just a season, it's a big part ..."
60,"Somewhere, Maybe Someone",(2020),\nDrama,\nBuilt-up tensions between four friends cut t...

In [73]:
#2021
for i in range(1,4163,250):
    url = "https://www.imdb.com/search/title/?title_type=feature&release_date=2021-01-01,2021-12-31&countries=us&count=250&start="+str(i)
    response = requests.get(url)
    #print(response.text[:500])
    html_soup = BeautifulSoup(response.text, 'html.parser')
    #type(html_soup)
    movie_containers = html_soup.find_all('div', class_ = 'lister-item mode-advanced')
    names = []
    years = []
    genres = []
    descriptions = []

    for container in movie_containers:
    
        if (container.find('span', attrs = {'class': 'genre'}) is not None)&\
            ((container.find_all('p', attrs={'class':'text-muted'})[-1].text)!='\nAdd a Plot\n'):

            # The name
            name = container.h3.a.text
            names.append(name)

            # The year
            year = container.h3.find('span', class_ = 'lister-item-year').text
            years.append(year)

            # The genres
            genre = container.find('span', attrs = {'class': 'genre'}).text
            genres.append(genre)

            # The descriptions
            description = container.find_all('p', attrs={'class':'text-muted'})[-1].text
            descriptions.append(description)
            
    test_df = pd.DataFrame({'movie': names,
                     'year': years,
                     'genres': genres,
                     'descriptions': descriptions})
    movie.append(test_df)

In [74]:
len(movie)

62

In [75]:
movie[61]

,movie,year,genres,descriptions
0,Hitorikko,(2021),\nHorror,\nA woman inherits a mysterious ancestral hous...
1,Sneaky Links,(2021),\nDrama,\nSneaky Link: When 2 people make arrangements...
2,Tell,(2021),\nDrama,\nSome connections last forever.
3,The Raven and the Rowan Tree,(2021),\nDrama,\nWhen a couple travels to an idyllic cottage ...
4,The Coup,(2021),\nDrama,\nAn Ethiopian State Department employee and a...
...,...,...,...,...
82,Impolite Boys,(2021),\nComedy,\nImpolite Boys is a dark comedy film that dep...
83,Tranquility: An Independent Short Film,(2021),"\nAction, Drama, Mystery",\nAfter being suddenly released from his life ...
84,Washingtonia,(2021),\nAnimation,\nFollows a rising political star and his inco...
85,A Man and His Gun,(2021),"\nCrime, Thriller",\nTwo young teenagers find themselves in a cas...
86,My House,(II) (2021),\nComedy,\nWitness the mystery unravel in one of the mo...

In [76]:
df_movie = pd.concat(movie)

In [78]:
df_movie.shape

(12347, 4)

In [80]:
df_movie.year.unique().tolist()

['(2018)',
 '(I) (2018)',
 '(II) (2018)',
 '(III) (2018)',
 '(V) (2018)',
 '(VIII) (2018)',
 '(IV) (2018)',
 '(XVI) (2018)',
 '(2019)',
 '(VI) (2018)',
 '(IX) (2018)',
 '',
 '(XXIII)',
 '(XVIII) (2018)',
 '(II)',
 '(I)',
 '(VII)',
 '(I) (2019)',
 '(III) (2019)',
 '(II) (2019)',
 '(V) (2019)',
 '(VII) (2019)',
 '(IV) (2019)',
 '(VI) (2019)',
 '(IX) (2019)',
 '(VIII) (2019)',
 '(X) (2019)',
 '(XXXV) (2019)',
 '(XII) (2019)',
 '(2020)',
 '(2021)',
 '(I) (2020)',
 '(II) (2020)',
 '(IV) (2020)',
 '(V) (2020)',
 '(XXI) (2020)',
 '(III) (2020)',
 '(VIII) (2020)',
 '(VI) (2020)',
 '(XI) (2020)',
 '(I) (2021)',
 '(IV) (2021)',
 '(III) (2021)',
 '(II) (2021)',
 '(V) (2021)',
 '(VI)',
 '(XII) (2021)']

In [91]:
df_movie = df_movie.reset_index(drop=True)

In [92]:
df_movie.tail()

,movie,year,genres,descriptions
12342,Impolite Boys,(2021),\nComedy,\nImpolite Boys is a dark comedy film that dep...
12343,Tranquility: An Independent Short Film,(2021),"\nAction, Drama, Mystery",\nAfter being suddenly released from his life ...
12344,Washingtonia,(2021),\nAnimation,\nFollows a rising political star and his inco...
12345,A Man and His Gun,(2021),"\nCrime, Thriller",\nTwo young teenagers find themselves in a cas...
12346,My House,(II) (2021),\nComedy,\nWitness the mystery unravel in one of the mo...

In [93]:
df_movie['year'][df_movie['year']=='']=np.nan
df_movie['year'][df_movie['year']=='(XXIII)']=np.nan
df_movie['year'][df_movie['year']=='(II)']=np.nan
df_movie['year'][df_movie['year']=='(I)']=np.nan
df_movie['year'][df_movie['year']=='(VII)']=np.nan
df_movie['year'][df_movie['year']=='(VI)']=np.nan

In [95]:
df_movie['year']=df_movie.year.ffill(axis = 0)

In [97]:
df_movie['year'] = df_movie['year'].str[-5:-1].astype(int)

In [98]:
df_movie['year'].unique()

array([2018, 2019, 2020, 2021])

In [99]:
df_movie.groupby("year").size().reset_index(name="#")

   year     #
0  2018  3360
1  2019  2906
2  2020  2932
3  2021  3149

In [102]:
df_movie["genres"] = df_movie["genres"].str.strip()
df_movie["descriptions"] = df_movie["descriptions"].str.strip()

In [104]:
df_movie.tail()

,movie,year,genres,descriptions
12342,Impolite Boys,2021,Comedy,Impolite Boys is a dark comedy film that depic...
12343,Tranquility: An Independent Short Film,2021,"Action, Drama, Mystery",After being suddenly released from his life se...
12344,Washingtonia,2021,Animation,Follows a rising political star and his incomp...
12345,A Man and His Gun,2021,"Crime, Thriller",Two young teenagers find themselves in a casca...
12346,My House,2021,Comedy,Witness the mystery unravel in one of the most...

In [106]:
df_movie['descriptions'][df_movie['movie']=='The Humans'].values

array(['Set inside a pre-war duplex in downtown Manhattan, The Humans follows the course of an evening in which the Blake family gathers to celebrate Thanksgiving. As darkness falls outside the ...                See full summary\xa0»'],
      dtype=object)

In [109]:
df_movie['descriptions'] = df_movie['descriptions'].str.replace('...                See full summary\xa0»','')

<ipython-input-109-872b4ce647a0>:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df_movie['descriptions'] = df_movie['descriptions'].str.replace('...                See full summary\xa0»','')

In [110]:
df_movie['descriptions'][df_movie['movie']=='The Humans'].values

array(['Set inside a pre-war duplex in downtown Manhattan, The Humans follows the course of an evening in which the Blake family gathers to celebrate Thanksgiving. As darkness falls outside the '],
      dtype=object)

In [111]:
df_movie['descriptions'][df_movie['movie']=='Madres'].values

array(["A Mexican-American couple expecting their first child relocate to a migrant farming community in 1970's California. When the wife begins to experience strange symptoms and terrifying "],
      dtype=object)

In [113]:
all_genres = df_movie["genres"].tolist()
all_genres = ", ".join(all_genres)
all_genres = sorted(list(set(all_genres.split(", "))))
all_genres

['Action',
 'Adventure',
 'Animation',
 'Biography',
 'Comedy',
 'Crime',
 'Drama',
 'Family',
 'Fantasy',
 'Game-Show',
 'History',
 'Horror',
 'Music',
 'Musical',
 'Mystery',
 'News',
 'Reality-TV',
 'Romance',
 'Sci-Fi',
 'Sport',
 'Talk-Show',
 'Thriller',
 'War',
 'Western']

In [115]:
for g in all_genres:
  df_movie[g] = df_movie["genres"].apply(lambda x: 1 if len(set(x.split(", ")).intersection(set([g]))) > 0 else 0)

In [116]:
df_movie.head()

,movie,year,genres,descriptions,Action,Adventure,Animation,Biography,Comedy,Crime,...,Mystery,News,Reality-TV,Romance,Sci-Fi,Sport,Talk-Show,Thriller,War,Western
0,Venom,2018,"Action, Adventure, Sci-Fi",A failed reporter is bonded to an alien entity...,1,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
1,Bohemian Rhapsody,2018,"Biography, Drama, Music",The story of the legendary British rock band Q...,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Avengers: Infinity War,2018,"Action, Adventure, Sci-Fi",The Avengers and their allies must be willing ...,1,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,Black Panther,2018,"Action, Adventure, Sci-Fi","T'Challa, heir to the hidden but advanced king...",1,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
4,A Quiet Place,2018,"Drama, Horror, Sci-Fi","In a post-apocalyptic world, a family is force...",0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0

In [117]:
df_movie.to_pickle('df_movie.pickle')